### ISSUE TITLE
Contribute this to tramp/emacs?

### ISSUE THREAD

**Issue by phil-s** [montag451/lxc-tramp#2]
This seems like something which would be useful as part of tramp.  Have you considered contributing it?

**Comment by montag451** [comment]
`lxc-tramp` is available through [melpa](https://melpa.org) so it's pretty easy to have it installed on your machine. Contributing to emacs seems to be [complicated](https://www.gnu.org/software/emacs/manual/html_node/emacs/Contributing.html) and I don't have the will nor the time to do it :stuck_out_tongue:

Anyway, thank you for the suggestion :+1: but I will close this since it's not really an issue
